### ISSUE TITLE
core: Add support for Tunnel Management Command

### ISSUE THREAD

**Issue by kyeyoon-eeum** [opencxl/opencxl#105]
7.6.7.3.1 Tunnel Management Command (Opcode 5300h) and Figure 7-20 in the spec.

7.6.7.4. MLD Component Command Set (passed to the MLD using the Tunnel Management Command)
- Get LD Info
- Get LD Allocations
- Set LD Allocations

Refer to `class BindVppbCommand()` for an example CCI implementation.

**Comment by zhxq** [comment]
I mainly focused on Tunnel Management Command and the connection between switch <-> MLD device in this issue. I've moved the part for 7.6.7.4. MLD Component Command Set to #111.
