### ISSUE TITLE
core: Fail unbind/bind scenarios

### ISSUE THREAD

**Issue by kyeyoon-eeum** [opencxl/opencxl#139]
Tracking various scenarios. Must work with the UI tool, not just the CLI. 

**FORMAT:** `<cmd>:<vcs>-<vppb-idx>-<ppb-idx>[<ld-ld, if applicable>]`

**1vcs_4sld.yaml**
- `unbind:0-0-1, bind:0-0-1` -> PASS
- `unbind:0-0-1, unbind:0-1-2, bind:0-1-1, bind:0-0-2` -> FAIL

**1vcs_2mlds.yaml**
- `unbind:0-1-1[1], bind:0-1-1[1]` -> FAIL
- `unbind:0-0-1[0], unbind:0-4-2[0], bind:0-4-1[0], bind:0-2-0[0]` -> FAIL 

**2vcs_8slds.yaml**
- `unbind:0-1-2, unbind:1-1-7, bind:0-1-7, bind:1-1-2` -> FAIL

**2vcs_1mld.yaml** (IMPORTANT: SC'24 MLD video configuration)
- `Start` -> FAIL
- `unbind:0-1-1[1], unbind:1-1-1[5], bind:1-1-1[1], bind:0-1-1[5]` -> UNABLE TO TEST

**Comment by arter97** [comment]
First 3: Juhyung
Last 1 (2vcs_1mld.yaml): Chanwoo

**Comment by arter97** [comment]
1vcs_4sld_2mlds.yaml

```
./cxl-util start -c fm -c switch -c sld-group -c mld-group -c host -c host-group --config-file configs/1vcs_4sld_2mlds.yaml 

./cxl-util fm unbind 0 5
./cxl-util fm unbind 0 6
./cxl-util fm bind 0 6 5 1
./cxl-util fm bind 0 5 5 2
```

Fails with `Exception: tid (90) already exists in the TLP table`.
